services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\CmsMcpPlugin\:
        resource: '../../src/*'
        exclude: '../../src/DependencyInjection/*'
